### ISSUE TITLE
Code doesn't work ..because of BColors library

### ISSUE THREAD

**Issue by adhara123007** [XavierTolza/python-timeseries-segmenter#1]
When I tried running the code 👍 

Traceback (most recent call last):
  File "demo.py", line 4, in <module>
    import dataframesegmenter as dfs
  File "/mnt/c/D_drive/ChangePoint/Labeller/l2/dataframesegmenter/__init__.py", line 1, in <module>
    from dataframesegmenter.segmenter import Segmenter
  File "/mnt/c/D_drive/ChangePoint/Labeller/l2/dataframesegmenter/segmenter.py", line 5, in <module>
    from BColors.BColors import colors
ImportError: No module named BColors

**Comment by XavierTolza** [comment]
Hum. Weird. Which OS and python version are you using? The Bcolors library sucks, sorry about that. Anyway the following commands run perfectly on my ubuntu 18.04 and python 2.7.15rc1:

``` bash
cd /tmp
git clone https://github.com/XavierTolza/python-timeseries-segmenter.git ts
cd ts
virtualenv venv
. venv/bin/activate
pip install -r requirements.txt
chmod +x demo.py
python ./demo.py
```

**Comment by adhara123007** [comment]
Here is my Ubuntu version:

Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial

And the python version
Python 2.7.15 :: Anaconda, Inc.

**Comment by XavierTolza** [comment]
Have you tried the small code I posted above?

Le 25/06/2018 à 16:37, adhara123007 a écrit :

**Comment by XavierTolza** [comment]
It's fixed in latest commit, i removed the library #172b36cf5b54ec1354fb469700ce51202347758c
